name: Run code quality

on:
  workflow_call:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install project dependencies
        run: yarn

      - name: Install ESLint formatter
        run: |
          yarn add @microsoft/eslint-formatter-sarif@3.0.0

      - name: Run ESLint
        run: yarn run eslint
          --config .eslintrc.js
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
